name: "Setup"
description: "Setup job"

inputs:
  ghcr_pat:
    required: true
    description: "token"

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: sh
