name: "Setup"
description: "Setup job"

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: sh
