name: Build
run-name: "'${{ github.actor }}' is building"

on:
  release:
    types:
      - released
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/github-aptions-practice:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ghcr-pat: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_NAME }}
