name: Run Code
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  release:
    types:
      - released
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stand:
        required: true
        type: choice
        options:
          - test
          - preprod
          - prod

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/github-aptions-practice:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker registry
        id: docker-login
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker registry
        id: docker-login
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Run Docker container
        run: docker run ${{ env.IMAGE_NAME }}
