name: Run Code
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  release:
    types:
      - released
  push:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/github-aptions-practice:latest

      - name: Run Docker image
        run: docker run ghcr.io/${{ github.repository_owner }}/github-aptions-practice:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/github-aptions-practice:latest
