name: Run Code
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t app .
      - name: Run Docker image
        run: docker run app
